### ISSUE TITLE
The -t switch for the "add" command does not prepend the current date to a task automatically when it's added.

### ISSUE THREAD

**Issue by oevl** [rprouse/dotnet-todo#55]
Working on Windows 10, compiled dotnet-todo from source code, found that the "-t" switch does not work:

```ToDo -t add "This is a todo item"```

Adds the item but without the current date

Looking at the code, seems like the variable ```addCreationDate``` is not getting assigned the value of  ```true```. 

Changing line 78 of TodoApplication.cs to:

```var command = new AddTaskCommand { Filename = Configuration.TodoFile, Task = text, AddCreationDate = true };```

Makes the program to always include the date before a newly created item.

**Comment by rprouse** [comment]
Weird, I use the -t all the time and it works for me but I'll look into it. I was actually thinking of making it the default because I like to have the dates on my todo's 😄 

It's nice to see other people are using this. Thanks for reporting.

**Comment by oevl** [comment]
Nice work porting todo.txt CLI to PowerShell, sorry can´t offer a PR,  don't know much about C# and could not find why the switch is not working.

**Comment by rprouse** [comment]
@oevl I still need to look at the code, but it seems to be working for me. This is an example, notice the date,

![image](https://user-images.githubusercontent.com/493828/128755917-3ee09c27-17d1-4127-8f7a-73409aff74cc.png)

Can you double check? Maybe you have another todo script in your path? You can check the version to see if it is mine, 

![image](https://user-images.githubusercontent.com/493828/128756060-fd064991-e4ea-4f5c-8ae4-8377fb3476e6.png)

Or `todo --help`

![image](https://user-images.githubusercontent.com/493828/128756150-55e16854-9e68-479a-94df-26dfe7210417.png)

**Comment by rprouse** [comment]
@oevl I haven't heard back from you so I am going to close.
